version: "3.8"
services:
  postgres:
    image: postgres:latest
    container_name: book_postgres
    command:
      - "postgres"
      - "-c"
      - "max_connections=200"
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=book_password
      - POSTGRES_DB=book_db
    ports:
      - 5432:5432
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U admin"]
      interval: 1m30s
      timeout: 30s
      retries: 5
      start_period: 30s
    volumes:
      - postgres-volume:/var/lib/postgresql/data

volumes:
  postgres-volume: